#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);


my $event = 'nethserver-portainer-update';
event_actions ( $event, 'initialize-default-databases' => '00');

event_actions($event, qw(
    nethserver-portainer_container 10
));


$event = 'portainer-upgrade';
event_actions($event, qw(
    nethserver-portainer_container 10
    ));
