#!/usr/bin/perl
use strict;

#search portainer PID and exist if valid
my $pid = qx('/usr/sbin/pidof portainer') || '';
return if ($pid);

#Create portainer container
system ('/usr/bin/docker run -d -p 9000:9000 --restart unless-stopped 
        --name portainer-container -v /var/lib/portainer:/data 
        -v "/var/run/docker.sock:/var/run/docker.sock" portainer/portainer') || die 'Cannot create portainer container';

