#!/usr/bin/bash

#search portainer PID and exist if valid
PID=`/usr/sbin/pidof portainer`;
if [[ $PID -ne '' ]]; then
    exit 0
fi

#Create portainer container
/usr/bin/docker run -d -p 9000:9000 --restart unless-stopped --name portainer-container \
    -v portainer-data:/data  -v "/var/run/docker.sock:/var/run/docker.sock" \
    portainer/portainer -H unix:///var/run/docker.sock
