#!/usr/bin/bash

event=$1
pid=`/usr/sbin/pidof portainer`

#default pki
crtFile=`/sbin/e-smith/config getprop pki CrtFile`
keyFile=`/sbin/e-smith/config getprop pki KeyFile`

#default certificate value
crt=${crtFile:-/etc/pki/tls/certs/NSRV.crt}
key=${keyFile:-/etc/pki/tls/private/NSRV.key}

#substitution
crt=${crt//'/etc/pki/tls/'/'/certs/'}
key=${key//'/etc/pki/tls/'/'/certs/'}

if [[ $pid -ne '' ]]; then
    /usr/bin/docker container stop portainer-container || exit 1
    /usr/bin/docker rm -f portainer-container || exit 1
fi

if [[ $event == 'portainer-upgrade' ]]; then
    /usr/bin/docker image pull portainer/portainer:latest || exit 1
fi

/usr/bin/docker run -d -p 9000:9000 --restart unless-stopped --name portainer-container \
    -v portainer-data:/data -v "/var/run/docker.sock:/var/run/docker.sock" \
    -v /etc/pki/tls/:/certs:ro portainer/portainer --ssl --sslcert "${crt}" \
    --sslkey "${key}" -H unix:///var/run/docker.sock || exit 1
